In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
a =np.array([])
b=np.array([2,3,23,4])
c=np.array([[23,4,3],[2,4,6]])

In [5]:
a

array([], dtype=float64)

In [17]:
a.size

0

In [9]:
type(a)

numpy.ndarray

In [15]:
a.ndim

1

In [6]:
b

array([ 2,  3, 23,  4])

In [18]:
b.size

4

In [10]:
type(b)

numpy.ndarray

In [16]:
b.ndim

1

In [7]:
c

array([[23,  4,  3],
       [ 2,  4,  6]])

In [20]:
c.shape

(2, 3)

In [19]:
c.size

6

In [11]:
type(c)

numpy.ndarray

In [2]:
import numpy as np

In [14]:
c.ndim

2

In [24]:
n = np.array([ [2,3,4,5] ,[20,10,23,43], [23,43,55,334] ]  )

In [25]:
n.shape

(3, 4)

In [3]:
print(n)

NameError: name 'n' is not defined

In [4]:
import numpy as np

In [5]:
n =np.array([ [2,3,4,5] ,[20,10,23,43], [23,43,55,334] ]  )

In [6]:
print(n)

[[  2   3   4   5]
 [ 20  10  23  43]
 [ 23  43  55 334]]


In [7]:
n[0][0]

2

In [9]:
n[2,[0,1]]

array([23, 43])

In [10]:
n[[0,1],1]

array([ 3, 10])

In [11]:
n[1][2]

23

In [12]:
n.shape

(3, 4)

In [17]:
n[2,[1,2]]

array([43, 55])

In [16]:
n[2,1:3]

array([43, 55])

In [18]:
n[[1,2],[2,3]]

array([ 23, 334])

In [20]:
n[1:,2:]

array([[ 23,  43],
       [ 55, 334]])

In [21]:
n[1:3,2:4]

array([[ 23,  43],
       [ 55, 334]])

In [22]:
n[3:]

array([], shape=(0, 4), dtype=int32)

In [23]:
n[0:3,3]

array([  5,  43, 334])

In [24]:
n[1,0:2]

array([20, 10])

# Arange

In [25]:
list(range(5,10))

[5, 6, 7, 8, 9]

In [26]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [27]:
list(range(4.2,3,2))

TypeError: 'float' object cannot be interpreted as an integer

In [28]:
np.arange(3.4,10)

array([3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

# RESHAPE

In [29]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
np.arange(12).reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [33]:
np.sqrt(81)

9.0

In [35]:
n.max()

334

In [36]:
n.min()

2

In [37]:
n.mean()

47.083333333333336

In [38]:
n.argmin()

0

In [39]:
n.argmax()

11

In [40]:
n*2

array([[  4,   6,   8,  10],
       [ 40,  20,  46,  86],
       [ 46,  86, 110, 668]])

In [41]:
n+10

array([[ 12,  13,  14,  15],
       [ 30,  20,  33,  53],
       [ 33,  53,  65, 344]])

In [42]:
n.sort()

In [43]:
n

array([[  2,   3,   4,   5],
       [ 10,  20,  23,  43],
       [ 23,  43,  55, 334]])

# RANDOM

In [44]:
np.random.rand(2,2)

array([[0.39233951, 0.52914803],
       [0.19661833, 0.19086656]])

In [45]:
np.random.rand(2)

array([0.84559944, 0.59160082])

In [46]:
np.random.rand(3,3)

array([[0.17390065, 0.27602164, 0.01784783],
       [0.81317182, 0.48323963, 0.1952287 ],
       [0.64501253, 0.18236184, 0.16891128]])

In [47]:
np.random.randn(2,2)

array([[-0.01128245,  0.72034938],
       [ 1.10290435,  0.78354614]])

In [50]:
np.random.randint(9,90,12)

array([29, 88, 79, 83, 64, 77, 66, 81, 73, 69, 69, 11])

In [56]:
s=np.random.randint(9,90,12).reshape(6,2)

# Summation

In [57]:
s.sum()

616

In [58]:
s.sum(axis=1)

array([ 89, 137, 120, 118,  38, 114])

In [59]:
s.sum(axis=0)

array([327, 289])

# 3D

In [62]:
d=np.array([[[4,50],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,50],[4,40],[6,60]]])

In [63]:
d.shape

(3, 3, 2)

In [64]:
d

array([[[ 4, 50],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 5, 50],
        [ 4, 40],
        [ 6, 60]]])

# Nan-not a number

In [72]:
x= np.array([12,36,np.nan,35,17,np.nan])

In [73]:
x

array([12., 36., nan, 35., 17., nan])

In [70]:
x.dtype

dtype('float64')